services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=idea_collab_svc'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: redis:latest
    container_name: idea-collab-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: idea-collab-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/idea_collab_svc
      SPRING_DATASOURCE_USERNAME: "myuser"
      SPRING_DATASOURCE_PASSWORD: "secret"
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/idea_collab_svc
      SPRING_DATASOURCE_USERNAME: "myuser"
      SPRING_DATASOURCE_PASSWORD: "secret"
    command: mvn test
